### ISSUE TITLE
Overflowing component when using Tailwind, Bootstrap, or other CSS frameworks that use .container

### ISSUE THREAD

**Issue by cjlryan** [efstajas/svelte-stepper#10]
Hey guys, properly great little component, a real time saver!

I've ran into a small but annoying bug when using tailwind where the internal "container" class clashes with tailwind and causes the layout to overflow beyond the screen width.

TLDR, the .container class adds 2rem of padding which increases the width of the element beyond the size of the scoped area.

My code:
```
<div class="relative w-full">
	<Stepper {steps} padding="0rem" />
</div>
```

Problematic code inside Stepper:
```
<div style="height: 248px; overflow: visible;" class="[[[container]]] svelte-1knpftn">
        <div class="step-container svelte-1knpftn">
                ...
```
Lots of CSS frameworks (Bootstrap, Tailwind etc) add styles to the .container class, and it appears to only be used to add a position: relative to the element so should be a simple fix.

Working on testing a PR for it now :)

**Comment by efstajas** [comment]
Included the fix in v0.2.2, thank you!
